# 02 - Data Cleaning

This notebook prepares a machine learning-ready dataset to study whether stellar properties can predict the presence of gas giant planets.

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/exoplanets_clean.csv")
df.head()

,pl_name,discoverymethod,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_rade,pl_radeerr1,pl_radeerr2,pl_radelim,...,st_loggerr1,st_loggerr2,st_logglim,st_age,st_ageerr1,st_ageerr2,st_agelim,sy_dist,sy_disterr1,sy_disterr2
0,11 Com b,Radial Velocity,323.21000,0.06,-0.05,0.0,NaN,NaN,NaN,NaN,...,0.08,-0.08,0.0,NaN,NaN,NaN,NaN,93.1846,1.9238,-1.9238
1,11 Com b,Radial Velocity,326.03000,0.32,-0.32,0.0,NaN,NaN,NaN,NaN,...,0.10,-0.10,0.0,NaN,NaN,NaN,NaN,93.1846,1.9238,-1.9238
2,11 Com b,Radial Velocity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,93.1846,1.9238,-1.9238
3,11 UMi b,Radial Velocity,516.21997,3.20,-3.20,0.0,NaN,NaN,NaN,NaN,...,0.07,-0.07,0.0,NaN,NaN,NaN,NaN,125.3210,1.9765,-1.9765
4,11 UMi b,Radial Velocity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.3210,1.9765,-1.9765

In [2]:
cols = [
    "pl_rade",   # needed to define gas giant label
    "st_teff",   # stellar temperature
    "st_rad",    # stellar radius
    "st_met",    # metallicity (IMPORTANT for your hypothesis)
    "st_age"     # stellar age
]

df_model = df[cols].copy()
df_model.head()

   pl_rade  st_teff  st_rad  st_met  st_age
0      NaN   4874.0   13.76   -0.26     NaN
1      NaN   4742.0   19.00   -0.35     NaN
2      NaN      NaN     NaN     NaN     NaN
3      NaN   4213.0   29.79   -0.02     NaN
4      NaN      NaN     NaN     NaN     NaN

In [3]:
df_model.isna().sum()

pl_rade    12414
st_teff     3603
st_rad      3412
st_met     14928
st_age     30120
dtype: int64

In [4]:
df_model = df_model.dropna()
df_model.shape

(5825, 5)

In [5]:
df_model["is_gas_giant"] = (df_model["pl_rade"] > 6).astype(int)
df_model.head()

      pl_rade  st_teff  st_rad  st_met  st_age  is_gas_giant
200  4.790000   3540.0   0.862    0.01  0.0190             0
201  3.956770   3678.0   0.744    0.23  0.0201             0
207  2.522021   3678.0   0.744    0.23  0.0201             0
212  2.790000   3540.0   0.862    0.01  0.0190             0
228  2.230000   5766.0   0.928   -0.15  3.3400             0

In [6]:
df_model["is_gas_giant"].value_counts()

is_gas_giant
0    4386
1    1439
Name: count, dtype: int64

In [7]:
X = df_model.drop(columns=["pl_rade", "is_gas_giant"])
y = df_model["is_gas_giant"]

X.head()

     st_teff  st_rad  st_met  st_age
200   3540.0   0.862    0.01  0.0190
201   3678.0   0.744    0.23  0.0201
207   3678.0   0.744    0.23  0.0201
212   3540.0   0.862    0.01  0.0190
228   5766.0   0.928   -0.15  3.3400

In [8]:
X.describe()

            st_teff       st_rad       st_met       st_age
count   5825.000000  5825.000000  5825.000000  5825.000000
mean    5513.316549     1.080069     0.027959     4.541782
std      705.012930     0.442603     0.168833     2.715959
min     2550.000000     0.117000    -0.760000     0.012100
25%     5194.000000     0.810000    -0.060000     2.750000
50%     5654.000000     0.980000     0.030000     4.170000
75%     5956.000000     1.270000     0.120000     5.620000
max    11327.000000     6.400000     0.790000    16.800000

In [9]:
df_model.to_csv("../data/processed/ml_ready_dataset.csv", index=False)

In [1]:
import sys
print(sys.executable)

/usr/local/bin/python3